# Generated by Django 4.2.17 on 2025-01-05 02:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuantityRooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите количество комнат (например, студия, однокомнатная, двухкомнатная и т. д.).', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('title', models.CharField(help_text='Краткое описание квартиры', max_length=200)),
                ('description', models.TextField(help_text='Введите описание квартиры', max_length=1000)),
                ('city', models.CharField(help_text='Город, где находится квартира', max_length=100)),
                ('street', models.CharField(help_text='Улица, где находится квартира', max_length=200)),
                ('house_number', models.CharField(help_text='Номер дома', max_length=10)),
                ('apartment_number', models.CharField(blank=True, help_text='Номер квартиры', max_length=10)),
                ('original_address', models.URLField(help_text='Уникальный URL с оригинального сайта', unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный ID квартиры', primary_key=True, serialize=False)),
                ('landlord', models.ForeignKey(help_text='Арендодатель квартиры', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.landlord')),
                ('quantity', models.ForeignKey(help_text='Выберите количество комнат', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.quantityrooms')),
            ],
            options={
                'ordering': ['city', 'street', 'house_number'],
            },
        ),
    ]
