# Generated by Django 4.2.17 on 2025-01-05 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landlord',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='last_name',
        ),
    ]
