# Generated by Django 4.2.17 on 2025-01-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_first_name_landlord_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'ordering': ['city', 'street', 'house_number', 'price']},
        ),
        migrations.AddField(
            model_name='home',
            name='price',
            field=models.CharField(default=18000, help_text='Цена аренды', max_length=10),
            preserve_default=False,
        ),
    ]
