# Generated by Django 4.2.17 on 2025-02-25 12:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_home_original_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='adrs',
            field=models.CharField(blank=True, help_text='Адрес из объявления', max_length=100),
        ),
        migrations.AddField(
            model_name='home',
            name='publication_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
