# Generated by Django 4.2.17 on 2025-02-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_homeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
    ]
